### ISSUE TITLE
rename to ido-files

### ISSUE THREAD

**Issue by alexanderjeurissen** [ido-nvim/files#1]
I think it would be good to prefix repo's in the org with `Ido-` as a naming convention.

That makes for less likely naming conflicts when cloning the repo for instance.

**Comment by shoumodip** [comment]
Actually, I was thinking why not remove the `ido-` prefix for every single repo here. This is the ido organization right? So there's not really anything that is *not* related to ido. So putting a `ido-` in front of everything is just redundant imo. I mean even without the prefix the repos are still identifiable as ido repositories like `ido-nvim/files` and `ido-nvim/git`.

**Comment by alexanderjeurissen** [comment]
Yeah it is a bit annoying when cloning repo's in GitHub as only the repo name is used and thus is very prone for conflicts.
but I just tested and it seems Github adds a number automatically to address these conflicts so I think we should be fine.
