### ISSUE TITLE
`ls` is not compatible with Mac OS / BSD systems

### ISSUE THREAD

**Issue by alexanderjeurissen** [ido-nvim/files#3]
https://github.com/ido-nvim/files/blob/c3022405c8eede084123b77d4461bd231eba1876/lua/ido-pkg/browse.lua#L19

The command used in the browse package is incompatible with the LS binary shipped with  Mac OS.

as such we might want to make the `ls` command configurable

see linked issue

**Comment by shoumodip** [comment]
Oh yeah I forgot that the `--group-directories-first` flag is only a privilege granted to GNU `ls`. I have just gotten used to the GNU coreutils being there in linux. To be fair I don't have any idea why the guys at Bell labs didn't make that default. Without that flag enabled, the output of `ls` just looks *dirty*.

I think I will postpond this a bit, since I am cleaning up the packages module a bit. I don't really like the code-base for the packages implementation as it currently stands. I can assure you though that this is the last major api change I have in mind for the time being.

**Comment by shoumodip** [comment]
BTW @alexanderjeurissen WDYT of this idea:
- Standard library of Ido functions (what I *should* have called packages to begin with)
- Standard library of Ido layouts and themes

So like one could get setup in just
```vim
Plug 'ido-nvim/core' " I will rename the ido-nvim/ido.nvim to this to get uniform naming scheme
Plug 'ido-nvim/std-fn' " Standard library of functions which leverage Ido
Plug 'ido-nvim/std-layout' " Pre-defined layouts like vertical, minimal, etc
Plug 'ido-nvim/std-theme' " Color-palletes for popular themes

**Comment by alexanderjeurissen** [comment]
> BTW @alexanderjeurissen WDYT of this idea:
> 
> * Standard library of Ido functions (what I _should_ have called packages to begin with)
> * Standard library of Ido layouts and themes
> 
> So like one could get setup in just
> 
> ```viml
> Plug 'ido-nvim/core' " I will rename the ido-nvim/ido.nvim to this to get uniform naming scheme
Fine with this rename, makes sense

> Plug 'ido-nvim/std-fn' " Standard library of functions which leverage Ido
Do we need a standard library for these functions ? I think having separate plugins for specific functionalities would be more flexible. Otherwise there is a risk that this plugin becomes very heavy and contains a lot of things one might not need.

> Plug 'ido-nvim/std-layout' " Pre-defined layouts like vertical, minimal, etc
I would rather split these up in separate repos, as I can reckon we will have plenty of layouts and combining them all in one repo again results in including layouts the end user might not need.

> Plug 'ido-nvim/std-theme' " Color-palletes for popular themes
I would not group all color palettes in a single repo for the same reason as above. Instead I think having separate repo's for varying color schemes, or even better creating pull-requests so common color schemes provide the ido-theme is a beter approach.

**Comment by alexanderjeurissen** [comment]
> Oh yeah I forgot that the `--group-directories-first` flag is only a privilege granted to GNU `ls`. I have just gotten used to the GNU coreutils being there in linux. To be fair I don't have any idea why the guys at Bell labs didn't make that default. Without that flag enabled, the output of `ls` just looks _dirty_.
> 
> I think I will postpond this a bit, since I am cleaning up the packages module a bit. I don't really like the code-base for the packages implementation as it currently stands. I can assure you though that this is the last major api change I have in mind for the time being.

Sure, while you revisit take a look at https://github.com/ido-nvim/core/issues/20 fixing that would address most of the pain points I'm currently experimenting with the package api.

**Comment by shoumodip** [comment]
Yeah you are right, it would be rather inflexible. Tell me what you think of this idea then.

A setup function which acts like a plugin manager but for Ido. So we don't need piles upon piles of `Plug 'ido-nvim/PLUGIN'`, but just a
```lua
require("ido.pkg").setup{
   files = {
      options = {
         command = "ls -AF",
      }
   },
   git = {}
}
```

It will download necessary packages. This will have one major advantage I can think of. **NO NAMING CONFLICTS**. We could clone the repos such that the complete directory tree of our plugins could be
```sh
plugins
├── vim-surround
├── ido.nvim
└── ido.pkg # The packages directory, NOT a git repo
    │
    ├── files # Git repo
    │   ├── browse.lua
    │   ├── cd.lua
    │   └── files.lua # Module name: files/files
    │
    └── git # Git repo
        ├── commits.lua
        └── files.lua # Module name: git/files
``` 

This will remove all chances of naming conflicts as in a git org, we can't have conflicting names.

Conflicts can actually happen in ido packages. Eg:
```sh
# repo 1
github.com/ido-nvim/files

# contains
ido-pkg/files.lua
ido-pkg/browse.lua

# repo 2
github.com/ido-nvim/git

# contains
ido-pkg/files.lua
ido-pkg/commits.lua
```

When you tell lua to load `ido-pkg/files`, which one will it load?

WDYT think of the plugin idea?

**Comment by alexanderjeurissen** [comment]
> WDYT think of the plugin idea?

I think we should leave plugin management to actual plugin managers. It seems that [packer.nvim](https://github.com/wbthomason/packer.nvim) is the leading package manager in the new lua neovim ecosystem. So we just need to make sure our plugins play nicely with `packer.nvim` and we should be good. But then again most plugin managers deal with plugins as `org/plugin` and given that we have control over the org I think we should be fine here.

I also don't think that `piles upon piles of Plug 'ido-nvim/PLUGIN'` is going to be a real problem, as evident in the popularity of plugin ecosystems that already use this pattern (denite.nvim, Telescope.nvim, etc). 

When it comes to flexibility as indicated in https://github.com/ido-nvim/core/issues/20 I think the only thing missing in the current packages API is a way for end-users to provide a option hash that can be consumed by the main entry point of ido packages. 

Addressing this should be relatively trivial, don't fret the current API is already actually pretty good (from package author perspective) we just need to solve this one use-case.

**Comment by shoumodip** [comment]
The new packages system accepts settings, so not a problem anymore.
