### ISSUE TITLE
Autoloading quirks

### ISSUE THREAD

**Issue by alexanderjeurissen** [ido-nvim/files#6]
### Context

https://github.com/ido-nvim/files/blob/3ecd430c55fe298ddb36af81e6582ef485e286cb/plugin/files.vim#L1-#L9

This form of autoloading does not play well with the way most lua plugins are setup.

For instance when defining the imports using `packer.nvim` (most prolific nvim-lua plugin manager)

```lua

use 'ido-nvim/files'

use { 'ido-nvim/core', config = function()
  local ido = require('ido')

  ido.pkg.setup('find_files', {
    opts = ...
  })
end}
```

breaks, because the package has not registered yet. I think in general the order in which dependencies are loaded is quite unreliable in vim.

### Proposed solution

I think we should forgo the notion of autoloading in  a `vimscript` plugin/pkg_name.vim file, and instead simply instruct the user to `require('ido-nvim/pkg')` somewhere in their `init.lua`. 

This would also nicely make all of ido `100% lua`

**Comment by shoumodip** [comment]
Got rid of the ugly viml.
